wouso/games/challenge/tests.py, wouso/resources/templates/profile/profile.html
=> No help pop-up for the CHALLENGE and REPORT buttons

README.md
Mention this in the README.md file.
=> Install libssl-dev package when installing wouso

wouso/interface/profile/forms.py, wouso/interface/profile/urls.py, wouso/interface/profile/views.py, wouso/resources/templates/profile/profile.html, wouso/resources/templates/registration/password_change_done.html, wouso/resources/templates/registration/password_change_form.html
=> [profile] Allow users to change their password

wouso/interface/apps/lesson/templates/lesson/category.html, wouso/interface/apps/lesson/templates/lesson/index.html, wouso/interface/apps/lesson/templates/lesson/tag.html, wouso/interface/apps/lesson/urls.py, wouso/interface/apps/lesson/views.py
=> [lesson] Update views/templates to better work with categories and tags

wouso/interface/apps/lesson/models.py, wouso/interface/apps/lesson/templates/lesson/cpanel/add_lesson.html, wouso/interface/apps/lesson/templates/lesson/cpanel/edit_lesson.html
Two fixes in the lesson module:
* Remove ending slash when including JavaScript file.
* Replace old `lesson_set()` function with `get_unordered_list()`.
=> Fixes in lesson

wouso/core/user/models.py, wouso/core/user/templatetags/user.py, wouso/games/quiz/models.py, wouso/interface/apps/lesson/migrations/0003_auto__add_field_lessoncategory_logo__add_field_lessontag_logo.py, wouso/interface/apps/lesson/models.py, wouso/interface/apps/lesson/templates/lesson/cpanel/add_lesson.html, wouso/interface/apps/lesson/templates/lesson/cpanel/manage_categories.html, wouso/interface/apps/lesson/templates/lesson/cpanel/manage_tags.html, wouso/interface/apps/lesson/templates/lesson/cpanel/sort_lessons.html, wouso/resources/static/css/cpanel-style.css, wouso/settings.py.example
- Add logo for lesson category and tag
- Fix breadcrumbs in cpanel/lessons
@razvand Do you want a logo for lessons as well?
=> Lessons logo

wouso/games/quiz/cpanel_urls.py, wouso/games/quiz/templates/quiz/cpanel/list_quizzes.html, wouso/interface/apps/files/cpanel_urls.py, wouso/interface/apps/files/templates/files/cpanel/list_files.html, wouso/interface/apps/lesson/cpanel_urls.py, wouso/interface/apps/lesson/templates/lesson/cpanel/list_lessons.html
Replace old pagination with <code>cpanel/pagination.html</code>
=> Specific pagination for Quiz, Lesson, Files

wouso/resources/templates/cpanel/manage_player.html
https://github.com/rosedu/wouso/issues/676
=> changed 'back to list' button

wouso/resources/templates/cpanel/add_formula.html
https://github.com/rosedu/wouso/issues/678
=> Add a Reset button and a Cancel button

wouso/resources/templates/cpanel/index.html
=> Remove duplicate date

wouso/resources/templates/cpanel/karma.html
https://github.com/rosedu/wouso/issues/682
=> message for no races on karma page

wouso/interface/apps/files/templates/files/cpanel/category.html
=> Add missing buttons

wouso/games/quiz/templates/quiz/cpanel/category.html, wouso/interface/apps/files/templates/files/cpanel/add_file.html, wouso/interface/apps/files/templates/files/cpanel/category.html, wouso/interface/forum/templates/forum/cpanel/add_category.html, wouso/interface/forum/templates/forum/cpanel/edit_category.html
=> Add edit/category extend manage categories template

wouso/resources/templates/cpanel/activity_monitor.html, wouso/resources/templates/cpanel/artifact_home.html, wouso/resources/templates/cpanel/artifactset.html, wouso/resources/templates/cpanel/bonus.html, wouso/resources/templates/cpanel/news.html, wouso/resources/templates/cpanel/players.html, wouso/resources/templates/cpanel/qpool_home.html, wouso/resources/templates/cpanel/reports.html, wouso/resources/templates/cpanel/spells_home.html
=> changed colspan=0 property

wouso/interface/apps/files/migrations/0001_add_unique.py, wouso/interface/apps/files/models.py
=> made file category names unique

wouso/games/quiz/migrations/0006_add_unique_name.py, wouso/games/quiz/models.py
=> Quiz category names are now unique.

wouso/interface/apps/lesson/tests.py
=> Made tests for unique LessonCategory and Lesson tag name

wouso/resources/templates/cpanel/activity_monitor.html, wouso/resources/templates/cpanel/artifact_home.html, wouso/resources/templates/cpanel/artifactset.html, wouso/resources/templates/cpanel/bonus.html, wouso/resources/templates/cpanel/news.html, wouso/resources/templates/cpanel/players.html, wouso/resources/templates/cpanel/qpool_home.html, wouso/resources/templates/cpanel/reports.html, wouso/resources/templates/cpanel/spells_home.html
This reverts commit 8f0212c91c61272abc2f313ab73edd2dc71b8e22.
=> Revert "changed colspan=0 property"

wouso/core/game/management/commands/wousoctl.py
Closes https://github.com/rosedu/wouso/issues/663
=> Pull request for 663-fix-setup

README.md, install.sh
```gherkin
As a mentor at ROSEdu CDL/Challenge
I lose valuable time with setting up the project steps
When I could automate this
```
=> Make a shell script to automatically do the install steps

wouso/core/tests.py, wouso/interface/cpanel/forms.py, wouso/interface/cpanel/tests.py, wouso/interface/cpanel/urls.py, wouso/interface/cpanel/views.py, wouso/resources/templates/cpanel/change_password.html, wouso/resources/templates/cpanel/manage_player.html
=> Fix change password issue in manage players, add tests

wouso/games/specialquest/models.py, wouso/games/specialquest/tests.py
=> Change 'remove user from special quest group' method, add test

wouso/games/teamquest/models.py, wouso/games/teamquest/tests.py
Remove redundant methods, rename fields and methods
=> [TeamQuest] Remove redundant methods, rename fields and methods

wouso/games/teamquest/models.py, wouso/games/teamquest/tests.py
=> Changed TeamQuestStatus highest/lowest level fields to Foreign Key Models

wouso/games/teamquest/models.py, wouso/games/teamquest/tests.py
=> [TeamQuest] Define TeamQuestStatus with subsequent classes TeamQuestLevelStatus and TeamQuestQuestion

wouso/games/teamquest/models.py, wouso/games/teamquest/tests.py
=> [TeamQuest] Define TeamQuestLevelStatus methods required for progress ca...lculation, define unicode

wouso/games/teamquest/utils/sample_team_quest.py
Script allows creation, cleanup and status report for sample team quest.
=> Add script for creating and removing a sample team quest

wouso/core/god/tests.py, wouso/core/user/utils.py
=> Use clear naming for default group

wouso/resources/static/css/cpanel-style.css, wouso/resources/templates/cpanel/races/all.html
Visually redesign groups page.
=> Change races / groups display mode

wouso/core/magic/manager.py, wouso/core/magic/tests.py, wouso/games/challenge/models.py, wouso/games/challenge/tests.py
@razvanch Have a look, please!
=> spells: refactor charge scoring and test

log/.gitignore, scripts/wousocron.bash
Sper că nu vă strică nimic.
cc @iulianR
=> Relative path

wouso/interface/cpanel/forms.py, wouso/resources/templates/cpanel/edit_question.html
=> Fix qotd edit when schedule is missing.

wouso/resources/templates/top/sidebar.html
Fixed first hacktoberfest bug! Yay
=> Changed Top to Menu on sidebar.

wouso/interface/tests.py
=> Right integration test

wouso/interface/cpanel/urls.py, wouso/interface/cpanel/views.py, wouso/resources/templates/cpanel/races/all.html, wouso/resources/templates/cpanel/races/group_edit.html
Added a template for the group edit button. Now, it won't redirect to an admin page and, rather, it will offer you the possibility to change a group.
=> Added template for edit group button

requirements-extra, wouso/interface/tests.py
=> Added test to check if username appears in last logged users.

wouso/interface/cpanel/urls.py, wouso/interface/cpanel/views.py, wouso/interface/views.py, wouso/resources/static/css/cpanel-style.css, wouso/resources/static/js/format.item.js, wouso/resources/templates/cpanel/players.html
Signed-off-by: Razvan Popa <razz.popa@gmail.com>
=> Repair cpanel player search

wouso/games/qotd/models.py
pep8 does not say anything anymore
=> Fixed models.py

wouso/interface/forum/tests.py
Added a suite of unit tests for the category module, testing if the the forum shows the specific text correctly.
=> added unit tests for the forum page, including category

wouso/games/challenge/models.py
=> Fix refused challenges being counted as lost

wouso/interface/cpanel/views.py, wouso/resources/templates/cpanel/activity_monitor.html
=> cpanel: add pagination for activity monitor

wouso/interface/profile/views.py
I've tried to find out when was this feature removed. But I haven't seen when was this variable deleted or if it was ever used.
=> Add back cast spell button to profiles

wouso/games/challenge/forms.py
=> Revert "Fix coding style"

wouso/games/challenge/forms.py
Fixed:
- some indendation problems
- "in" instead of .has_key() which is deprecated
Fixes https://github.com/rosedu/wouso/issues/786
=> Fixed Lint game/challenge/api.py #786

wouso/interface/apps/pages/models.py
=> Fixed TextBox in News Item

wouso/interface/apps/qproposal/forms.py, wouso/resources/templates/qproposal/propose.html, wouso/resources/templates/site_base.html
=> Qproposal: Populate tags when changing category

wouso/settings.py.example
=> Add cookie auto-refresh

wouso/resources/templates/cpanel/manage_player.html
- reset button added
- buttons added at the bottom of the form as requested
=> http://i.imgur.com/JZyGccL.png
=> Fixed: Align form buttons in Manage Player page #850

wouso/resources/templates/cpanel/index.html
=> Send alert when a link is accessed without permission.

wouso/resources/templates/cpanel/add_player.html, wouso/resources/templates/cpanel/add_spell.html, wouso/resources/templates/cpanel/edit_spell.html, wouso/resources/templates/cpanel/qpool_add_tag.html, wouso/resources/templates/cpanel/qpool_edit_tag.html, wouso/resources/templates/cpanel/races/create.html, wouso/resources/templates/cpanel/races/edit_race.html, wouso/resources/templates/cpanel/races/group_create.html, wouso/resources/templates/cpanel/races/group_edit.html
@gabrielivascu can you review this? I hope it's ok now. xD
=> Added cancel/reset buttons #845

wouso/interface/apps/messaging/models.py, wouso/locale/ro_RO/LC_MESSAGES/django.po
=> Real names and date will appear now in Django Admin #832

.codeclimate.yml
I added the .codeclimate.yml exception file as requested here => #867
This is the final and the good commit, sorry for the problems created earlier.
=> Add codeclimate.yml exception file

wouso/resources/templates/cpanel/manage_player.html
=> cpanel/players: Fix template error by moving misplaced template tag

wouso/core/config/fixtures/initial_data.json, wouso/core/config/models.py, wouso/core/god/god.py, wouso/interface/activity/achievements.py, wouso/interface/cpanel/models.py
=> Configure Head Start date from CPanel

wouso/core/__init__.py, wouso/core/common.py, wouso/core/config/fixtures/initial_data.json, wouso/core/config/fixtures/test_data.json, wouso/core/config/models.py, wouso/core/config/tests.py, wouso/core/security/sec.py, wouso/core/tests.py, wouso/interface/apps/magic/views.py, wouso/interface/cpanel/models.py, wouso/interface/cpanel/tests.py, wouso/interface/profile/views.py, wouso/interface/top/models.py, wouso/interface/views.py
Fixes #891 
@gabrielivascu Have a look
=> Customization refactoring

wouso/resources/templates/magic/bazaar.html
=> Show suggestive message in exchange tab when exchange is disabled
